name: Release

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'The name of releasing library: Angular Core, Angular UI Control'
        required: true
        default: 'Angular Core'
      increment:
        description: 'The increment: major, minor or patch'
        default: 'patch'

jobs:
  stable:
    name: Release package ${{ github.event.inputs.package }}-${{ github.event.inputs.increment }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Check yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **\node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install yarn dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      # - name: Build Hulk
      #   run: yarn build:all --skip-nx-cache

      - name: Release Library
        # run: node ./scripts/release-it.js --path packages/prettier-plugin-formatter --ci
        run: yarn nx run ui-controls:release ${{ github.event.inputs.package }} --${{ github.event.inputs.increment }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: 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
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
